name: PYPI Publish
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      publishTag: ${{ steps.setup.outputs.publishTag }}
      aaaa: ${{ steps.setup.outputs.aaaa }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        name: setup python
        with:
          python-version: "3.11"
      - name: subprocess
        id: setup
        shell: python
        run: |
          import subprocess
          from pathlib import Path
          aaaa = "/".join(str(Path('../..').resolve()).split('/') + ['pyproject.toml'])
          version = (
              Path(aaaa)
              .read_text(encoding="utf8")
              .split("version = ")[1]
              .split("\n")[0]
              .strip('"')
          )
          subprocess.run('echo "aaaa='+aaaa+'" >> "$GITHUB_OUTPUT"', shell=True)
          subprocess.run('echo "publishTag=v'+version+'" >> "$GITHUB_OUTPUT"', shell=True)
  publish:
    name: publish
    needs: prepare
    runs-on: ubuntu-latest
    env:
      PUBLISHTAG: ${{needs.prepare.outputs.publishTag}}
    steps:
      - run: echo "$PUBLISHTAG"
      - run: echo "${{needs.prepare.outputs.publishTag}}"
      - run: echo "${{needs.prepare.outputs.aaaa}}"
