name: PYPI Publish
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      publishTag: ${{ steps.setup.outputs.publishTag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        name: setup python
        with:
          python-version: "3.11"
      - name: subprocess
        id: setup
        shell: python
        run: |
          import subprocess
          subprocess.run('echo "publishTag=v1" >> "$GITHUB_OUTPUT"')
  publish:
    name: publish
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - env:
          PUBLISHTAG: ${{needs.prepare.outputs.publishTag}}
        run: echo "$PUBLISHTAG"
