name: PYPI Publish
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup.outputs.version }}
      aaaa: ${{ steps.setup.outputs.aaaa }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        name: setup python
        with:
          python-version: "3.11"
      - name: subprocess
        id: setup
        shell: python
        run: |
          import subprocess
          import pathlib
          import urllib.request
          import json

          aaaa = urllib.request.urlopen("https://pypi.org/pypi/dvc/json")
          data = json.dumps(json.load(
            urllib.request.urlopen("https://pypi.org/pypi/dvc/json")
          ))
          version = (
              pathlib.Path('pyproject.toml')
              .read_text(encoding="utf8")
              .split("version = ")[1]
              .split("\n")[0]
              .strip('"')
          )
          subprocess.run('echo "aaaa='+str(data)+'" >> "$GITHUB_OUTPUT"', shell=True)
          subprocess.run('echo "version=v'+version+'" >> "$GITHUB_OUTPUT"', shell=True)
  publish:
    name: publish
    needs: prepare
    runs-on: ubuntu-latest
    env:
      version: ${{needs.prepare.outputs.version}}
    steps:
      - run: echo "${{needs.prepare.outputs.version}}"
      - run: echo "${{needs.prepare.outputs.aaaa}}"
